public class CombinationOfKeyPad {

    /*
     * Write a program to find the letter comibnations that can be generated by pressing the digits
     * of a keypad starting from 1 - 9.
     * Ex = "12"
     * O/P = []
    */

    
    
}
